[media]
    upload= "upload"
    transfer= "censor"
[grpc]
    enable = true
    port = ":7781"
    path = "/tmp/node.sock"
[rest]
    enable = true

[[oss]]
   endpoint ="https://oss-cn-shanghai.aliyuncs.com"
   access_key_id=""
   access_key_secret =""
   bucket_name =""

[callback]
       type = "grpc"
       back_type = "unix"
       back_addr ="/tmp/manager.sock"