// Code generated by protoc-gen-go. DO NOT EDIT.
// source: censor.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValidateRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ObjectKey            string   `protobuf:"bytes,2,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_censor_b4efcba6e1907405, []int{0}
}
func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (dst *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(dst, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ValidateRequest) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *ValidateRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type RemoteDownloadRequest struct {
	ObjectKey            string   `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	BackHost             string   `protobuf:"bytes,4,opt,name=backHost,proto3" json:"backHost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteDownloadRequest) Reset()         { *m = RemoteDownloadRequest{} }
func (m *RemoteDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteDownloadRequest) ProtoMessage()    {}
func (*RemoteDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_censor_b4efcba6e1907405, []int{1}
}
func (m *RemoteDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDownloadRequest.Unmarshal(m, b)
}
func (m *RemoteDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDownloadRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDownloadRequest.Merge(dst, src)
}
func (m *RemoteDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteDownloadRequest.Size(m)
}
func (m *RemoteDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDownloadRequest proto.InternalMessageInfo

func (m *RemoteDownloadRequest) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *RemoteDownloadRequest) GetBackHost() string {
	if m != nil {
		return m.BackHost
	}
	return ""
}

type CensorReply struct {
	Code                 int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail               *CensorReplyDetail `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CensorReply) Reset()         { *m = CensorReply{} }
func (m *CensorReply) String() string { return proto.CompactTextString(m) }
func (*CensorReply) ProtoMessage()    {}
func (*CensorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_censor_b4efcba6e1907405, []int{2}
}
func (m *CensorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CensorReply.Unmarshal(m, b)
}
func (m *CensorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CensorReply.Marshal(b, m, deterministic)
}
func (dst *CensorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CensorReply.Merge(dst, src)
}
func (m *CensorReply) XXX_Size() int {
	return xxx_messageInfo_CensorReply.Size(m)
}
func (m *CensorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CensorReply.DiscardUnknown(m)
}

var xxx_messageInfo_CensorReply proto.InternalMessageInfo

func (m *CensorReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CensorReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CensorReply) GetDetail() *CensorReplyDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

type CensorReplyDetail struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Json                 string   `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CensorReplyDetail) Reset()         { *m = CensorReplyDetail{} }
func (m *CensorReplyDetail) String() string { return proto.CompactTextString(m) }
func (*CensorReplyDetail) ProtoMessage()    {}
func (*CensorReplyDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_censor_b4efcba6e1907405, []int{3}
}
func (m *CensorReplyDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CensorReplyDetail.Unmarshal(m, b)
}
func (m *CensorReplyDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CensorReplyDetail.Marshal(b, m, deterministic)
}
func (dst *CensorReplyDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CensorReplyDetail.Merge(dst, src)
}
func (m *CensorReplyDetail) XXX_Size() int {
	return xxx_messageInfo_CensorReplyDetail.Size(m)
}
func (m *CensorReplyDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CensorReplyDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CensorReplyDetail proto.InternalMessageInfo

func (m *CensorReplyDetail) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CensorReplyDetail) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterType((*ValidateRequest)(nil), "proto.ValidateRequest")
	proto.RegisterType((*RemoteDownloadRequest)(nil), "proto.RemoteDownloadRequest")
	proto.RegisterType((*CensorReply)(nil), "proto.CensorReply")
	proto.RegisterType((*CensorReplyDetail)(nil), "proto.CensorReplyDetail")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CensorServiceClient is the client API for CensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CensorServiceClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*CensorReply, error)
}

type censorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCensorServiceClient(cc *grpc.ClientConn) CensorServiceClient {
	return &censorServiceClient{cc}
}

func (c *censorServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*CensorReply, error) {
	out := new(CensorReply)
	err := c.cc.Invoke(ctx, "/proto.CensorService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CensorServiceServer is the server API for CensorService service.
type CensorServiceServer interface {
	Validate(context.Context, *ValidateRequest) (*CensorReply, error)
}

func RegisterCensorServiceServer(s *grpc.Server, srv CensorServiceServer) {
	s.RegisterService(&_CensorService_serviceDesc, srv)
}

func _CensorService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensorServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CensorService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensorServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CensorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CensorService",
	HandlerType: (*CensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _CensorService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "censor.proto",
}

func init() { proto.RegisterFile("censor.proto", fileDescriptor_censor_b4efcba6e1907405) }

var fileDescriptor_censor_b4efcba6e1907405 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xcf, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0xca, 0x07, 0x08, 0x83, 0x3f, 0xe2, 0x24, 0x9a, 0x0d, 0xf1, 0x60, 0x7a, 0xf2, 0xd4,
	0x10, 0x3c, 0xe8, 0x19, 0x7b, 0x90, 0x78, 0xc1, 0x25, 0xf1, 0xbe, 0xdd, 0x4e, 0x6a, 0xb1, 0xed,
	0x20, 0xbb, 0x68, 0xf8, 0xef, 0x8d, 0x43, 0x51, 0xa1, 0xa7, 0x9d, 0x79, 0x6f, 0xf6, 0xbd, 0x97,
	0x07, 0xc7, 0x96, 0x2a, 0xc7, 0xab, 0x68, 0xb9, 0x62, 0xcf, 0xd8, 0x91, 0x27, 0x9c, 0xc3, 0xd9,
	0x8b, 0x29, 0xf2, 0xd4, 0x78, 0xd2, 0xf4, 0xbe, 0x26, 0xe7, 0xf1, 0x14, 0x5a, 0xd3, 0x58, 0x05,
	0xd7, 0xc1, 0x4d, 0x5f, 0xb7, 0xa6, 0x31, 0x5e, 0x41, 0x9f, 0x93, 0x05, 0x59, 0xff, 0x44, 0x1b,
	0xd5, 0x12, 0xf8, 0x17, 0x40, 0x84, 0xb6, 0xdf, 0x2c, 0x49, 0xfd, 0x17, 0x42, 0xe6, 0xf0, 0x19,
	0x2e, 0x34, 0x95, 0xec, 0x29, 0xe6, 0xcf, 0xaa, 0x60, 0x93, 0xee, 0xa4, 0xf7, 0xa4, 0x82, 0x43,
	0xa9, 0x21, 0xf4, 0x12, 0x63, 0xdf, 0x1e, 0xd9, 0x79, 0xd5, 0x16, 0xf2, 0x67, 0x0f, 0x4b, 0x18,
	0x3c, 0x48, 0x7c, 0x4d, 0xcb, 0x42, 0x5c, 0x2d, 0xa7, 0x24, 0x1a, 0x1d, 0x2d, 0x33, 0x2a, 0x38,
	0x2a, 0xc9, 0x39, 0x93, 0x51, 0x9d, 0x72, 0xb7, 0xe2, 0x08, 0xba, 0x29, 0x79, 0x93, 0x17, 0x92,
	0x72, 0x30, 0x56, 0xdb, 0x0e, 0xa2, 0x3f, 0x8a, 0xb1, 0xf0, 0xba, 0xbe, 0x0b, 0xef, 0xe0, 0xbc,
	0x41, 0x36, 0x8a, 0x41, 0x68, 0x2f, 0x1c, 0x57, 0xb5, 0x9b, 0xcc, 0xe3, 0x29, 0x9c, 0x6c, 0x3f,
	0xce, 0x69, 0xf5, 0x91, 0x5b, 0xc2, 0x7b, 0xe8, 0xed, 0x0a, 0xc6, 0xcb, 0xda, 0xf7, 0xa0, 0xf1,
	0x21, 0x36, 0xf3, 0x84, 0xff, 0x26, 0x23, 0x50, 0x96, 0xcb, 0x28, 0xcb, 0xfd, 0xeb, 0x3a, 0x89,
	0x32, 0x4e, 0x2d, 0x57, 0xd9, 0xf6, 0x72, 0x82, 0x7b, 0x26, 0xb3, 0x6f, 0x6c, 0x16, 0x24, 0x5d,
	0x21, 0x6f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xeb, 0x44, 0x8a, 0xea, 0x01, 0x00, 0x00,
}
